# Generated by Django 3.2 on 2021-05-04 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksys', '0002_auto_20210502_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_pic',
            field=models.FileField(upload_to='book_covers/'),
        ),
    ]
