# Generated by Django 3.2 on 2021-05-04 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksys', '0003_alter_book_cover_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_pic',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
