# Generated by Django 3.2 on 2021-05-07 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksys', '0005_alter_book_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='message',
            name='title',
            field=models.CharField(max_length=256),
        ),
    ]
